### PR TITLE
Adds powershell script to install dependent packages in windows

### PR DESCRIPTION
**Pull request by waliahimanshu**
To test this script
1) open windows powershell console
2) navigate to the directory where scripts are placed
3) run the script by typing   .\InstallDependencies.ps1

This will be ideally run from a bootstrap folder where vagrant file is placed.

### CODE REVIEW

**Comment by byteknacker** [comment]
Very readable code, thanks but I have one question:

adds_powershell_script_to_instal_dependent_packages_in_windows_by_waliahimanshu_ _pull_request__84_ _devblend_zenias

**Comment by byteknacker** [comment]
The code is ok though, I will test it tomorrow on Windows.

**Comment by waliahimanshu** [comment]
Hi @byteknacker Is there a reason to close this PR ?

**Comment by ghost** [comment]
@waliahimanshu we are closing all current issues and pull requests. We are going to be starting from scratch again.

**Comment by waliahimanshu** [comment]
oh, Okay make sense then.

**Pull request closed without merging**
