### PR TITLE
Add CONTRIBUTING.md For Better Workflow of Collaborators

### PR DESCRIPTION
**Pull request by byteknacker**
Please have a look at this and let me know what to add or remove. I hope that this will add to our productivity and improve collaborator's communication.

### CODE REVIEW

**Comment by alayek** [comment]
Awesome job!!

# LGTM :+1:

Let's :shipit: :package:

**Comment by zcassini** [comment]
Looks good.
I'm will have to observe the commit style guidelines.

**Comment by byteknacker** [comment]
@zcassini basically the more details on why and how you coded something is important. I will add some more good materials on git commit style so our commit messages are really good.

**Comment by byteknacker** [comment]
@zcassini would you do the honour to merge this one? I am not allowed to merge my own PR per guideline. ;-)

**Pull request merged**
