### PR TITLE
Requesting a pull to byteknacker:master from byteknacker:gitconfigdir

### PR DESCRIPTION
**Pull request by byteknacker**
Finish Github and Git integration

Major changes in the bash scripts.

### CODE REVIEW

**Comment by byteknacker** [comment]
Please review this one. Many many thanks for your time!

**Comment by byteknacker** [comment]
Closes #22

**Comment by koustuvsinha** [comment]
Tested on Ubuntu 14.04, works perfectly! :+1:

**Comment by byteknacker** [comment]
I am so glad to hear that. Thanks!

**Comment by byteknacker** [comment]
@alayek either I do this merge manually or I make another PR and we merge the other one.

**Comment by alayek** [comment]
It still has my commits. I am not sure if this should be merged without rebasing.

**Comment by byteknacker** [comment]
I shall rebase this now. I will try using some fake branches locally first.

**Comment by alayek** [comment]
@byteknacker did you manage to rebase this to exclude my commits?

**Comment by abhisekp** [comment]
@byteknacker the "Closes #22" must be written in the PR message https://github.com/byteknacker/fcc-python-vagrant/pull/34#issue-156233941 :point_up:

**Pull request closed without merging**
