### PR TITLE
<Mass murdering> Zeus. Check is needed

### PR DESCRIPTION
**Pull request by mtancoigne**
Please, review for any mistake...

### CODE REVIEW

**Comment by mtancoigne** [comment]
Yes, it's forked from the master...

I'll try to achieve the other living PRs before you get any interest in this victory...

**Comment by ghost** [comment]
@mtancoigne you should be targeting this PR to the `dev` branch...

**Comment by byteknacker** [comment]
Shall we call the staging branch dev or staging?

**Comment by byteknacker** [comment]
@mtancoigne there are some conflicts, now sure which.

**Comment by byteknacker** [comment]
@mtancoigne I think the merge of the last PR of readme created this new conflict.

**Comment by mtancoigne** [comment]
Dev branch was inexistant when i started :)

**Comment by byteknacker** [comment]
@mtancoigne yes sorry I should have made things work before you commit. I will finish the architecture and workflow tomorrow to lay a stone in simple PR workflow.

**Pull request closed without merging**
