### PR TITLE
Add Linux install script, needs testing

### PR DESCRIPTION
**Pull request by ghost**
# DO NOT MERGE, Requires Testing

@alayek @byteknacker @raisedadead @koustuvsinha  Linux Install Script, requires testing. If you can, test it in your systems. Advance warning : it might be buggy :stuck_out_tongue_closed_eyes: 

**Please see comments from previous PR (https://github.com/DevBlend/DevBlend/pull/21)**

### CODE REVIEW

**Comment by byteknacker** [comment]
@koustuvsinha please give me a step by step instruction on how to test your script on my Mac?

**Comment by byteknacker** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by koustuvsinha** [comment]
@byteknacker just simply run the script `./install.sh` or `sh install.sh`

**Comment by byteknacker** [comment]
@koustuvsinha I think this installation script will be obsolete once we have distributed our package managers. But can you please keep your code because I think it might be useful later on.

**Comment by koustuvsinha** [comment]
@byteknacker cool i'm not deleting my branch

**Comment by byteknacker** [comment]
Ok perfect!

**Pull request closed without merging**
