### PR TITLE
Add tests

### PR DESCRIPTION
**Pull request by alayek**
I have added some more tests.

### CODE REVIEW

**Comment by byteknacker** [comment]
LGTM 👍 

default__vagrant_

**Comment by byteknacker** [comment]
@koustuvsinha did you have a test run on this PR?

**Comment by alayek** [comment]
@raisedadead you might wanna review this PR and if everything goes fine, please merge. 

**Comment by BKinahan** [comment]
Tested add-tests branch on Mac, LGTM

```
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/vagrant/.virtualenvs/fcc-py3/bin/python3
cachedir: .cache
rootdir: /vagrant/tests, inifile:
collected 8 items

test_modules/django_test.py::TestDjango::test_django_version PASSED
test_modules/git_test.py::TestGit::test_git_version PASSED
test_modules/os_test.py::TestOs::test_uname_kernel PASSED
test_modules/os_test.py::TestOs::test_uname_os PASSED
test_modules/psql_test.py::TestPsql::testPsqlConnection PASSED
test_modules/psql_test.py::TestPsql::testPsqlDatabase PASSED
test_modules/venv_test.py::TestVenv::test_python_version PASSED
test_modules/venv_test.py::TestVenv::test_venv_activated PASSED

=========================== 8 passed in 0.33 seconds ===========================
```

**Comment by raisedadead** [comment]
```
 Successfully installed py-1.4.31 pytest-2.9.1                                                                                          
(fcc-py3) [vagrant](git:add-tests*) $ py.test -v                                                                                       
========================================================= test session starts =========================================================

platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/vagrant/.virtualenvs/fcc-py3/bin/python3                
cachedir: .cache                                                                                                                       
rootdir: /vagrant, inifile:                                                                                                            
collected 8 items                                                                                                                      

tests/test_modules/django_test.py::TestDjango::test_django_version PASSED                                                              
tests/test_modules/git_test.py::TestGit::test_git_version PASSED                                                                       
tests/test_modules/os_test.py::TestOs::test_uname_kernel PASSED                                                                        
tests/test_modules/os_test.py::TestOs::test_uname_os PASSED                                                                            
tests/test_modules/psql_test.py::TestPsql::testPsqlConnection PASSED                                                                   
tests/test_modules/psql_test.py::TestPsql::testPsqlDatabase PASSED                                                                     
tests/test_modules/venv_test.py::TestVenv::test_python_version PASSED                                                                  
tests/test_modules/venv_test.py::TestVenv::test_venv_activated PASSED                                                                  

====================================================== 8 passed in 0.94 seconds =======================================================

```

**Pull request merged**
