### PR TITLE
add a fix for #13

### PR DESCRIPTION
**Pull request by alayek**
# DON'T Merge

This is a small fix for what was reported in #13. Let the filer try it out and once everyone has tested on their system, we can merge.

@mtancoigne please verify by pulling this branch and running `vagrant up` on your Windows box.

### CODE REVIEW

**Comment by byteknacker** [comment]
Agreed, will test it out tonight.

**Comment by mtancoigne** [comment]
Tested on windows 10 with latest vagrant and virtualbox : It works without problem :+1: 

```
================================================================== test session starts ===================================================================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/vagrant/.virtualenvs/fcc-py3/bin/python3
cachedir: .cache
rootdir: /vagrant/tests, inifile:
collected 5 items

test_modules/git_test.py::TestGit::test_git_version PASSED
test_modules/os_test.py::TestOs::test_uname_kernel PASSED
test_modules/os_test.py::TestOs::test_uname_os PASSED
test_modules/psql_test.py::TestPsql::testPsqlConnection PASSED
test_modules/psql_test.py::TestPsql::testPsqlDatabase PASSED

================================================================ 5 passed in 0.47 seconds ================================================================
```

**Comment by koustuvsinha** [comment]
working ok in Ubuntu. should I merge it now?

**Comment by byteknacker** [comment]
@koustuvsinha please let me test it as well. Just in a few min.

**Comment by byteknacker** [comment]
@koustuvsinha yes please. I have no objections.

**Comment by alayek** [comment]
Actually, let @raisedadead test this one as well before merging. He has Windows.

**Comment by byteknacker** [comment]
default__vagrant__and_venv_test_py_ __users_john_desktop_repositories_opensource_fcc-python-vagrant_and_fcc-python-vagrant_specs_-_google_docs

**Comment by byteknacker** [comment]
It does not break anything on Mac OS X.

**Comment by alayek** [comment]
Cool! Thanks @byteknacker :smile: 

Let @raisedadead verify then he would merge.

**Comment by BKinahan** [comment]
Tested on Mac, LGTM

```
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/vagrant/.virtualenvs/fcc-py3/bin/python3
cachedir: .cache
rootdir: /vagrant, inifile:
collected 5 items

tests/test_modules/git_test.py::TestGit::test_git_version PASSED
tests/test_modules/os_test.py::TestOs::test_uname_kernel PASSED
tests/test_modules/os_test.py::TestOs::test_uname_os PASSED
tests/test_modules/psql_test.py::TestPsql::testPsqlConnection PASSED
tests/test_modules/psql_test.py::TestPsql::testPsqlDatabase PASSED

=========================== 5 passed in 0.24 seconds ===========================
```

**Comment by raisedadead** [comment]
image

#### :sparkles: :sparkles: **LGTM.** :sparkles: :sparkles:

Thanks @alayek !

**Pull request merged**
