### PR TITLE
Add feature of automatic git remote add origin <newgithubrepo>

### LINKED ISSUE #55: Auto add git remote add origin <newurl> upon zeus gitcreate
Robert mentioned that when he used zeus gitcreate private, he still has to manually git clone from the Github website. This can be avoided by auto detecting the https_url value of the json file generated by accessing the Github API and after having created the new git repo. 

Add this functionality to zeus source code so users don't have to struggle with setting up this themselves.

### PR DESCRIPTION
**Pull request by byteknacker**
- Based on the request of @robeerob this feature automatically
  tracks the newly created GitHub remote repository
  which was initiated by "zeus gitcreate public/private"
- It autoruns git remote add origin <newgithubrepo>
- It autoruns git push --set-upstream origin master
  so that the user can just "git push"
  instead of using "git push origin master"

Tested locally and works for John Wu on Mac OS 10.11.05

Closes #55

### CODE REVIEW

**Comment by byteknacker** [comment]
Did anyone test this PR?

**Comment by ghost** [comment]
@byteknacker, gonna pull this down and test it now :stuck_out_tongue_winking_eye:

**Comment by ghost** [comment]
#### I'm currently having the following errors:

**On setup:**

``` bash
==> default: mv: 
==> default: cannot stat ‘/vagrant/zeus’
==> default: : No such file or directory
```

**First time running `vagrant ssh`**:

``` bash
chmod: cannot access ‘/home/vagrant/.configs/zeus’: No such file or directory
error: could not lock config file .git/config: No such file or directory
Do you want to setup Github? [y/N] >>> y
-bash: /home/vagrant/.configs/zeus: No such file or directory
```

This is due to the recent switch from `zeus` to `DevBlend`.

**Comment by alayek** [comment]
@atjonathan no, that was there earlier as well. I know which lines in the scripts are giving this error. Will push a fix soon.

**Comment by byteknacker** [comment]
We have to refactor the code anyways so most of our current PR will be just merged and then refactored. But the idea of this feature is important since it automates lots of steps for a common task.

**Comment by ghost** [comment]
I will try this again tonight... (**Reminder**)

**Comment by byteknacker** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by byteknacker** [comment]
Ok, I will merge this one. Sorry for breaking the rules, but it will stagnate if I don't. I tested it a few times and it works perfectly

**Pull request merged**
