### PR TITLE
New Zeus script for all langages

### PR DESCRIPTION
**Pull request by ghost**
Updated the zeus script. Don't attach any importance at the branch name, nothing's related to PHP beside the fact I only tested with my box.

So the big changes : 
- Zeus script is called `zeus -l <language> -d <destination> -o <option>`
- Every repo should have a `/vagrant/vagrant/_provision_vars.sh` with at least `export V_WORKING_DIR='some/path'`, the path being the absolute path where the git repo must be initialized.
- You can use the `-o` option to create variations on your provisionning (look at [how I did it](https://github.com/alayek/zeus/blob/PHP-zeus-script-test/php/vagrant/provision.sh#L115)
- In the `/vagrant/vagrant/` dir of the created box, a file named `zeus_credentials.sh` is copied. It contains the script to authenticate to github/heroku and init a git repo in the `V_WORKING_DIR`

I think that's all the changes, but for now you don't have to bother with implementing a .bashrc to achieve this.

@alayek Maybe the best way to merge this without breaking anything would be to merge the PHP branch first, as this one is a fork.

### CODE REVIEW

**Comment by byteknacker** [comment]
Where are the conflicts coming from. The way I resolve them is to pull this particular PR with the GitHub wrapper gh (node version) and then create from the dev of your fork which should be in sync with dev of main repo another mock or topic branch. So now you have one topic branch from dev, another PR branch from PR. You merge locally only on branch dev and with branch PR. Now you are essentially replicating an exact duplicate of a hypothetical version of the dev on main repo if we were to really merge this PR. You definitely get some conflicts now, you resolve those conflicts. Now you check out to dev. Then you merge on the dev with the topic branch. You are on dev locally. You make another semantic branch which attaches meaning to your edits tracking your dev. You raise a new PR and close the previous PR and state in it a reference to the new PR. Now others test especially the initial contributor who raise the first PR. Wow that is a mouthful. Hope it makes sense.

**Comment by alayek** [comment]
@atjonathan seems this branch has merge conflicts. Please resolve.

**Comment by atjonathan** [comment]
I will try this again tonight... (**Reminder**)

**Comment by byteknacker** [comment]
I think this branch somehow messed around with the previous change to the zeus main script. The commits are somehow taken from previous PRs. @mtancoigne I know it might be a bit of a pain but could you please delete this PR and raise another one only with your one single commit of the changed zeus script?

**Comment by byteknacker** [comment]
To be made a new by @mtancoigne

**Pull request closed without merging**
