### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### DevBlend/DevBlend now has a Chat Room on Gitter

@atjonathan has just created a chat room. You can visit it here: [https://gitter.im/DevBlend/DevBlend](https://gitter.im/DevBlend/DevBlend?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/DevBlend/DevBlend?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by ghost** [comment]
This was an accidental creation :stuck_out_tongue_closed_eyes:

**Comment by byteknacker** [comment]
@atjonathan did you raise this one? Shall we have our own chat or should we use FCC? I think FCC has more traction on gitter.

**Comment by ghost** [comment]
@byteknacker, no i accidentally created a chat room and a bot picked it up or something. I think we should have our own chat room personally.

**Comment by byteknacker** [comment]
@atjonathan ok, we have a chat about this in the Slack team channel. The point is that it might be too much overhead to have three chats.

**Pull request closed without merging**
