### PR TITLE
Fix install : Remove Red Texts

### LINKED ISSUE #18: Red coloured printouts as though they are errors
During the provisioning process of vagrant up, there are three occasions where it persistently prints out the stdout in the terminal in red colour as though they are some sort of errors. Of course, due to the semantic of the printout it is conclusive that they are not errors at all. But it would be good for the aesthetic that they are printed out normally in green colour as it is standard for vagrant provisioning. 

The three occasions are:
1. Postgres installation and setup of psql database.
2. stdout mistake printout as appearing on the vagrant source code repo's issues.
3. Heroku toolbelt installation.

default__vagrant__and_slack
default__bash__and_readme_md_ __users_john_desktop_repositories_opensource_fcc-python-vagrant_and_slack
default__bash_

### PR DESCRIPTION
**Pull request by alayek**
Updated the `provision.sh` to
- group all installs together
- do pretty printing
- remove some of the red texts during set up

Partially closes #18

### CODE REVIEW

**Comment by BKinahan** [comment]
Tested on Mac, LGTM

```
============================= test session starts ==============================
platform linux -- Python 3.4.3, pytest-2.9.1, py-1.4.31, pluggy-0.3.1 -- /home/vagrant/.virtualenvs/fcc-py3/bin/python3
cachedir: .cache
rootdir: /vagrant, inifile:
collected 5 items

tests/test_modules/git_test.py::TestGit::test_git_version PASSED
tests/test_modules/os_test.py::TestOs::test_uname_kernel PASSED
tests/test_modules/os_test.py::TestOs::test_uname_os PASSED
tests/test_modules/psql_test.py::TestPsql::testPsqlConnection PASSED
tests/test_modules/psql_test.py::TestPsql::testPsqlDatabase PASSED

=========================== 5 passed in 0.22 seconds ===========================
```

**Comment by koustuvsinha** [comment]
Tested on Ubuntu. **LGTM** :+1:

**Comment by byteknacker** [comment]
Testing now, will merge if successful.

**Comment by byteknacker** [comment]
Simple vagrant up after git clone:

default__vagrant__and_fix_install___remove_red_texts_by_alayek_ _pull_request__20_ _byteknacker_fcc-python-vagrant

Using zeus.py

default__vagrant__and_fix_install___remove_red_texts_by_alayek_ _pull_request__20_ _byteknacker_fcc-python-vagrant

There is an error: cannot stat ‘/vagrant/.bashrc’

So I am still inside the fcc-py3 virtualenv but not in the synced folder upon vagrant ssh

However, pytest yields that everything passed.

@alayek why is this? Do I need to update zeus.py? I think we should deprecate zeus.py and make it to zeus.sh with the progress by @koustuvsinha so far on #21 

default__vagrant__and_fix_install___remove_red_texts_by_alayek_ _pull_request__20_ _byteknacker_fcc-python-vagrant

**Comment by byteknacker** [comment]
Won't merge yet since there is this unresolved zeus.py isseu.

**Comment by alayek** [comment]
@byteknacker it's an issue in `zeus.py`. The file you are looking for is `/home/vagrant/.bashrc`, Which is same as `~/.bashrc` for `vagrant` user.

You are searching for that in `/vagrant`. Do you want me to update `zeus.py` as part of this PR?

**Comment by byteknacker** [comment]
Yes please update it if you can. You just have to read on docs for plumbum

**Comment by alayek** [comment]
Actually I thought we would write `zeus.py` as `zeus.sh` or a form of Makefile. Nonetheless, if you don't get error with vanilla `vagrant up` method, it's better to merge this one.

**Comment by byteknacker** [comment]
@alayek ok I am testing now for vanilla vagrant up. I should deprecate zeus.py for this release and use the combined effort to make zeus generalised for all common OS and more stable.

**Comment by byteknacker** [comment]
LGTM, must be an issue of zeus.py.

**Pull request merged**
