### PR TITLE
adding script to install dependencies in windows #24

### PR DESCRIPTION
**Pull request by waliahimanshu**
This possibly needs some testing on few systems as I only tested this on a windows running on parallel desktop.

### CODE REVIEW

**Comment by alayek** [comment]
I will test it on my Win 10 and Win 7.

**Comment by byteknacker** [comment]
Thanks for this PR @waliahimanshu

**Comment by byteknacker** [comment]
Does this work so far? Should we merge it? I have not tested since I don't have Windows yet.

**Comment by byteknacker** [comment]
@waliahimanshu  would you mind to change the destination of your PR from DevBlend:master to DevBlend:dev?

**Comment by waliahimanshu** [comment]
sure will do in a bit, I hope someone get time to test this.

**Comment by byteknacker** [comment]
I will get a Windows next week and start also testing. @alayek did you check this out? @koustuvsinha you have a Windows right?

**Comment by byteknacker** [comment]
@waliahimanshu I am going to test this on my Windows, how do I do it? What are the steps. Please detail them out to me with bullet points. 1, 2, 3, etc. I need the exact steps and please make it without many gaps. I am not very familiar with Windows dev yet.

**Comment by byteknacker** [comment]
To be made anew

**Pull request closed without merging**
