### PR TITLE
Change basebox to minimal

### PR DESCRIPTION
**Pull request by koustuvsinha**
Changed basebox from "ubuntu/trusty64" to "minimal/trusty64". Tested provisioning script is working :white_check_mark:

### CODE REVIEW

**Comment by alayek** [comment]
What was the download size and time (preferably on your home network :stuck_out_tongue: )?

**Comment by byteknacker** [comment]
I basically got these two errors using the minimal/trusty64 box on two separate runs. I also logged it in Slack. No idea why I get it on Mac OS. Normally this should not happen.

error 1
error 2

**Comment by zoeyronain** [comment]
I found a version that seems to be smaller: ubuntu/xenial64. it's 270mb base. haven't checked the script yet though.

**Comment by alayek** [comment]
@siadevelopment Wouldn't xenial64 be  Ubuntu 16.04? Are we sure we want to move to Ubuntu 16.04 so early after release last month?

**Comment by zoeyronain** [comment]
@alayek I don't see a problem with it, my dev servers at work, and my personal servers (that are on ubuntu) are fine. It's just a suggestion.

Edit: Granted, 99% of my linux machines are CentOS

**Comment by alayek** [comment]
Wow!

@koustuvsinha @byteknacker take a look at this :+1: 

I think we should give Ubuntu 16.04 a try.

**Comment by byteknacker** [comment]
@siadevelopment well done, I am now testing if ubuntu/xenial64 is working.

**Comment by byteknacker** [comment]
@koustuvsinha it is working now on mine as well. I just had to install the newest version of Virtual box and add the extension pack. Now closing this and merging.

**Comment by byteknacker** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request merged**
