### PR TITLE
Ruby vagrant : further edits

### PR DESCRIPTION
**Pull request by zcassini**
Adds some packages the todomvc app needed to support capybara.
Cleans, comment organize the code more.
Renames provision2.sh to install-gems.sh
Redirects the chruby error  (that i have to live with)
Adds size in MiB of files to be downloaded in echo comments.

### CODE REVIEW

**Comment by zcassini** [comment]
cd /vagrant
git clone https://github.com/zcassini/todomvc_on_rails_with_test
cd todomvc_on_rails_with_test
bundle install
rake db:create
rake db:migrate
rails s -b 0.0.0.0   #for localhost:3000  on your host
heroku create
git push heroku master
heroku run rake db:migrate 
- go check out your newly deployed todomvc app!

**Comment by byteknacker** [comment]
@zcassini would you mind to change the destination of your PR from DevBlend:master to DevBlend:dev?

**Comment by ghost** [comment]
@byteknacker, you can't change the target branch. I'll submit a new PR (#76) with the fix.

**Comment by atjonathan** [comment]
See #78 for new PR...

**Pull request closed without merging**
