### PR TITLE
adding script to install dependencies in windows

### PR DESCRIPTION
**Pull request by waliahimanshu**
Creating same pull request to DevBlend:dev branch

### CODE REVIEW

**Comment by byteknacker** [comment]
Are those previous commit part of your PR? Would they make duplicate entries in the Dev and master branches?

**Comment by waliahimanshu** [comment]
They are not, they are there when i synced my local origin with master upstream. No they won't make duplicate entries.

**Comment by byteknacker** [comment]
Ok that is fine then. Just wondering. I think I had something similar and thought it will create duplicates then only made matters worse with squashing.

**Comment by ghost** [comment]
I believe those commits will make duplicates. Try rebasing and dropping the unwanted commits.

**Comment by byteknacker** [comment]
@waliahimanshu isn't this a duplicate of #41? Please check since I am really sure that this will create duplicate entries in our history of git commits. In doubt, please remove all your PR and restart another one from your fork with a semantic name of your local branch to zenias/dev. Please specify dev explicitly as it is not by default anymore.

You don't have to do much apart from putting your existing code into a new branch on your fork. Please back them up before, lest we should loose your valuable code. I took a look and it looks very solid. 

I just need to test it once and it will be merged.

**Comment by byteknacker** [comment]
This will be made anew

**Pull request closed without merging**
