### PR TITLE
Dev ruby

### PR DESCRIPTION
**Pull request by zcassini**
Switch form the older Librarian to the newer Berksfile cookbook manager.

Berksfile seems all around faster and is fast enough at downloading cookbooks that I can take them out of the repo and let them be downloaded at provision time.

This does require a plugin for vagrant though `vagrant plugin install vagrant-berksfile'

### CODE REVIEW

**Comment by byteknacker** [comment]
@zcassini is that only required for ruby for now? Do you reckon we need it for all the stack?

**Comment by alayek** [comment]
@zcassini ok I will test this. But there are too many files (328) in one commit. Are these files autogenerated? If so, include only the ones that can generate these.

**Comment by byteknacker** [comment]
@alayek I think these files are deleted, they existed before in our repo.

**Comment by zcassini** [comment]
Yes these are the cookbooks files being deleted.

**Comment by alayek** [comment]
The README needs to be updated. The plugin is `vagrant-berkshelf`, not `vagrant-berksfile`.

**Comment by alayek** [comment]
Also, I am getting this error:

``` zsh
➜  ruby git:(ruby) vagrant plugin install vagrant-berkshelf
Installing the 'vagrant-berkshelf' plugin. This can take a few minutes...
Installed the plugin 'vagrant-berkshelf (4.1.0)'!
Post install message from the 'vagrant-berkshelf' plugin:

The Vagrant Berkshelf plugin requires Berkshelf from the Chef Development Kit.
You can download the latest version of the Chef Development Kit from:

    https://downloads.chef.io/chef-dk/

Installing Berkshelf via other methods is not officially supported.

```

**Comment by zcassini** [comment]
Well that is a bummer.    I don't much see the point in  having a plugin if you have to dowload it anyhow.
Lemmie see what I can do about this.

**Comment by alayek** [comment]
Works well!

``` zsh
➜  ruby git:(ruby) date && vagrant up > logfile.txt && date
Thu Jun  2 00:15:23 IST 2016
Thu Jun  2 00:35:55 IST 2016
```

Wish it were a bit faster though. I have logged in and done the tests with version of Ruby, Rails etc.

# LGTM :+1:

Let's :shipit: :package:

**Pull request merged**
