### PR TITLE
Architecture restructuring with zeus now centralised

### PR DESCRIPTION
**Pull request by byteknacker**
- zeus is now one bash script
- zeus has now one more sub command and option

Run the following to test
1. cd ~/Desktop
2. git clone https://github.com/alayek/zeus.git
3. Remain in ~/Desktop
4. chmod 755 ~/Desktop/zeus/zeus
5. ~/Desktop/zeus/zeus create -python newproject
6. Enjoy the magic

So the commandline syntax is:

zeus create -python newproject

   where zeus is the main command which is invoking the bash script

   create is the sub command to create a new project directory with vm

   -python is the option for Python stack

### CODE REVIEW

**Comment by llamatarianism** [comment]
LGTM :+1:

**Comment by alayek** [comment]
You missed copying the `tests` directory.

**Comment by zcassini** [comment]
No errors here. :100:

**Comment by byteknacker** [comment]
@alayek do we have to copy the test directory? It is only for collaborators and testers but not for endusers right? I want to keep it for the user as simple as possible without any distractions.

**Comment by alayek** [comment]
Ideally, we should have a `test` mode and `production` mode. In test mode, we do copy the test directory, but in production mode, the end users won't need to do that.

**Comment by alayek** [comment]
# LGTM :+1:

Let's :shipit: :package:

We will fix the issues after merge.

**Comment by byteknacker** [comment]
Yes I will add a test option flag to Zeus!

**Pull request merged**
